# Copyright (c) 2022 Huawei Technologies Co.,Ltd.
#
# openGauss is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

# Format of this configuration file:
# <metric_prefix>:
# query: <common query command>
# metrics:
#   - <metric_suffix>:
#     subquery: <read the execution result of common query command
#                from standard input stream, and filter
#                the result by using the subquery>
#     usage: <type>
#     description: <description text, optional>
#   ...


gaussdb_cluster:
  query: "cm_ctl query -Cvip"
  timeout: 5
  metrics:
    - state:
        subquery: grep cluster_state | awk '{if ($3=="Normal") print 1; else print 0}'
        usage: "GAUGE"
        description: "cluster state, 0 meaning abnormal and 1 meaning normal"
    - primary:
        subquery: grep -E "P Primary" | sed 's/|/\n/g' | grep -E "Primary" | awk '{printf "%s:%s\n",$3,$5}'
        usage: "LABEL"
        description: "primary node list"
    - standby:
        subquery: grep -E "P Primary" | sed 's/|/\n/g' | grep -E "Primary" | awk '{printf "%s:%s\n",$3,$5}' | sed -z 's/\n/,/g'
        usage: "LABEL"
        description: "standby node list"
    - normal:
        subquery: grep -E "P Primary" | sed 's/|/\n/g' | grep -E "Normal" | awk '{printf "%s:%s\n",$3,$5}' | sed -z 's/\n/,/g'
        usage: "LABEL"
        description: "standby node list"

gaussdb_progress:
  query: "ps -aux | grep gaussdb"
  timeout: 5
  metrics:
    - cpu_usage:
        subquery: awk '{print $3}'
        usage: "GAUGE"
        description: "cpu usage of gaussdb process"
    - mem_usage:
        subquery: awk '{print $4}'
        usage: "GAUGE"
        description: "mem usage of gaussdb process"
    - user:
        subquery: awk '{print $1}'
        usage: "LABEL"
        description: "all of users who have gaussdb process"
    - pid:
        subquery: awk '{print $2}'
        usage: "LABEL"
        description: "pid of gaussdb process"
