# Copyright (c) 2022 Huawei Technologies Co.,Ltd.
#
# openGauss is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

pg_settings:
  name: pg_settings
  desc: OpenGauss database settings
  query:
    - name: pg_settings
      sql: "select name,
             case when vartype = 'bool' then
              (case when setting = 'on' then 1. else 0. end) else setting::float end as setting,
             vartype from pg_settings
             where vartype not in ('enum', 'string')
             and name not similar to '(audit_%|dcf_%|debug_%|password_%)';"
      version: '>=0.0.0'
      timeout: 1
      status: enable

  metrics:
    - name: name
      description: GUC name
      usage: LABEL
    - name: setting
      description: GUC value
      usage: GAUGE
    - name: vartype
      description: GUC type
      usage: LABEL

  status: enable
  ttl: 600
  timeout: 1
