version: '1.0'
name: pr-pipeline
displayName: PRPipeline
triggers:
  trigger: auto
  pr:
    branches:
      include:
        - master
stages:
  - name: build
    displayName: build
    strategy: naturally
    trigger: auto
    steps:
      - step: build@python
        name: build_python
        displayName: Python build
        pythonVersion: '3.9'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - ''
          - cd ${GITEE_REPO}
          - python3 -m pip install -r requirements-x86.txt
          - python3 -m pip install pytest
          - ''
          - python3 -m pytest tests
          - ''
        caches: []
        notify: []
        strategy:
          retry: '0'
  - name: stage-d714bf41
    displayName: test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: ut@python
        name: unit_test_python
        displayName: Python unit test
        pythonVersion: '3.9'
        commands:
          - cd ${GITEE_REPO}
          - ''
          - ''
          - ''
          - pytest --html=report/index.html
        report:
          path: report
          index: index.html
        checkpoints:
          - key: TestPassRate
            value: 100
            logicalOperator: '&&'
            relationalOperator: '>='
        caches: []
        notify: []
        strategy:
          retry: '0'
strategy:
  blocking: false
