version: '1.0'
name: pr-pipeline
displayName: PRPipeline
triggers:
  trigger: auto
  pr:
    branches:
      include:
        - master
stages:
  - name: test
    displayName: test
    strategy: naturally
    trigger: auto
    steps:
      - step: ut@python
        name: unit_test_python36
        displayName: Python36_old
        pythonVersion: '3.6'
        commands:
          - git clone https://gitee.com/opengauss/openGauss-DBMind.git
          - cd openGauss-DBMind
          - pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements-x86.txt
          - pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -i pytest
          - pytest --html=report/index.html
        report:
          path: report
          index: index36.html
        checkpoints:
          - key: TestPassRate
            value: 100
            logicalOperator: '&&'
            relationalOperator: '>='
        caches: []
        notify: []
        strategy:
          retry: '0'
      - step: ut@python
        name: unit_test_python38
        displayName: Python38_new
        pythonVersion: '3.8'
        commands:
          - git clone https://gitee.com/opengauss/openGauss-DBMind.git
          - cd openGauss-DBMind
          - pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements-x86.txt
          - pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -i pytest
          - pytest --html=report/index.html
        report:
          path: report
          index: index38.html
        checkpoints: []
        caches: []
        notify: []
        strategy:
          retry: '0'
