version: '1.0'
name: pr-pipeline
displayName: PRPipeline
triggers:
  trigger: auto
  pr:
    branches:
      include:
        - master
stages:
  - name: test
    displayName: test
    strategy: naturally
    trigger: auto
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: python3.9-slim-docker
        certificate: ''
        image: docker.io/python:3.9-slim
        command:
          - apt update
          - ''
          - apt install wget -y
          - apt install zip -y
          - ''
          - mkdir workspace
          - cd workspace
          - ''
          - wget -O master.zip https://gitee.com/opengauss/openGauss-DBMind/repository/archive/master.zip
          - unzip master.zip
          - ''
          - cd openGauss-DBMind-master
          - ''
          - python3 -m pip install -r requirements-x86.txt
          - python3 -m pip install pytest
          - ''
          - python3 -m pytest tests
          - ''
          - ''
        notify: []
        strategy:
          retry: '0'
