version: '1.0'
name: pr-pipeline
displayName: PRPipeline
triggers:
  trigger: auto
  pr:
    branches:
      include:
        - master
stages:
  - name: test
    displayName: test
    strategy: naturally
    trigger: auto
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: python3.9-slim-docker
        certificate: ''
        image: docker.io/python:3.9-slim
        command:
          - cd ${GITEE_REPO}
          - python3 -m pip install -r requirements-x86.txt || git clone -b py39-linux-amd64 --depth 1 https://gitee.com/opengauss/openGauss-DBMind-3rd 3rd
          - python3 -m pip install pytest
          - ''
          - python3 -m pytest tests
          - ''
        notify: []
        strategy:
          retry: '0'
