version: '1.0'
name: pr-pipeline
displayName: PRPipeline
triggers:
  trigger: auto
  pr:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: build
    strategy: naturally
    trigger: auto
    steps:
      - step: build@python
        name: build_python
        displayName: Python build
        pythonVersion: '3.9'
        commands:
          - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - ''
          - 'ls -l '
          - env
          - 'git --version '
          - ''
          - python3 -m pip install -r requirements-x86.txt
          - python3 -m pip install pytest
          - ''
          - python3 -m pytest tests
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        strategy: {}
